;; generated file, do not edit
(defpackage #:spirv-core
  (:use )
  (:export #:pair-id-ref-id-ref
           #:execution-model
           #:memory-access
           #:shader
           #:sampler-addressing-mode
           #:literal-sampler
           #:groups
           #:kernel
           #:geometry
           #:pipe-storage
           #:literal-integer
           #:storage-class
           #:id-ref
           #:function-control
           #:dim
           #:addressing-model
           #:id-memory-semantics
           #:loop-control
           #:pair-literal-integer-id-ref
           #:addresses
           #:group-operation
           #:literal-context-dependent-number
           #:derivative-control
           #:decoration
           #:pipes
           #:pair-id-ref-literal-integer
           #:capability
           #:sparse-residency
           #:memory-model
           #:selection-control
           #:matrix
           #:access-qualifier
           #:id-scope
           #:named-barrier
           #:device-enqueue
           #:literal-string
           #:literal-spec-constant-op-integer
           #:source-language
           #:image-query
           #:id-result-type
           #:geometry-streams
           #:id-result
           #:image-operands
           #:execution-mode
           #:image-format
           #:sampler-filter-mode
           #:subgroup-dispatch
           #:literal-ext-inst-integer
           #:nop
           #:undef
           #:source-continued
           #:source
           #:source-extension
           #:name
           #:member-name
           #:string
           #:line
           #:extension
           #:ext-inst-import
           #:ext-inst
           #:memory-model
           #:entry-point
           #:execution-mode
           #:capability
           #:type-void
           #:type-bool
           #:type-int
           #:type-float
           #:type-vector
           #:type-matrix
           #:type-image
           #:type-sampler
           #:type-sampled-image
           #:type-array
           #:type-runtime-array
           #:type-struct
           #:type-opaque
           #:type-pointer
           #:type-function
           #:type-event
           #:type-device-event
           #:type-reserve-id
           #:type-queue
           #:type-pipe
           #:type-forward-pointer
           #:constant-true
           #:constant-false
           #:constant
           #:constant-composite
           #:constant-sampler
           #:constant-null
           #:spec-constant-true
           #:spec-constant-false
           #:spec-constant
           #:spec-constant-composite
           #:spec-constant-op
           #:function
           #:function-parameter
           #:function-end
           #:function-call
           #:variable
           #:image-texel-pointer
           #:load
           #:store
           #:copy-memory
           #:copy-memory-sized
           #:access-chain
           #:in-bounds-access-chain
           #:ptr-access-chain
           #:array-length
           #:generic-ptr-mem-semantics
           #:in-bounds-ptr-access-chain
           #:decorate
           #:member-decorate
           #:decoration-group
           #:group-decorate
           #:group-member-decorate
           #:vector-extract-dynamic
           #:vector-insert-dynamic
           #:vector-shuffle
           #:composite-construct
           #:composite-extract
           #:composite-insert
           #:copy-object
           #:transpose
           #:sampled-image
           #:image-sample-implicit-lod
           #:image-sample-explicit-lod
           #:image-sample-dref-implicit-lod
           #:image-sample-dref-explicit-lod
           #:image-sample-proj-implicit-lod
           #:image-sample-proj-explicit-lod
           #:image-sample-proj-dref-implicit-lod
           #:image-sample-proj-dref-explicit-lod
           #:image-fetch
           #:image-gather
           #:image-dref-gather
           #:image-read
           #:image-write
           #:image
           #:image-query-format
           #:image-query-order
           #:image-query-size-lod
           #:image-query-size
           #:image-query-lod
           #:image-query-levels
           #:image-query-samples
           #:convert-f-to-u
           #:convert-f-to-s
           #:convert-s-to-f
           #:convert-u-to-f
           #:u-convert
           #:s-convert
           #:f-convert
           #:quantize-to-f16
           #:convert-ptr-to-u
           #:sat-convert-s-to-u
           #:sat-convert-u-to-s
           #:convert-u-to-ptr
           #:ptr-cast-to-generic
           #:generic-cast-to-ptr
           #:generic-cast-to-ptr-explicit
           #:bitcast
           #:s-negate
           #:f-negate
           #:i-add
           #:f-add
           #:i-sub
           #:f-sub
           #:i-mul
           #:f-mul
           #:u-div
           #:s-div
           #:f-div
           #:u-mod
           #:s-rem
           #:s-mod
           #:f-rem
           #:f-mod
           #:vector-times-scalar
           #:matrix-times-scalar
           #:vector-times-matrix
           #:matrix-times-vector
           #:matrix-times-matrix
           #:outer-product
           #:dot
           #:i-add-carry
           #:i-sub-borrow
           #:u-mul-extended
           #:s-mul-extended
           #:any
           #:all
           #:is-nan
           #:is-inf
           #:is-finite
           #:is-normal
           #:sign-bit-set
           #:less-or-greater
           #:ordered
           #:unordered
           #:logical-equal
           #:logical-not-equal
           #:logical-or
           #:logical-and
           #:logical-not
           #:select
           #:i-equal
           #:i-not-equal
           #:u-greater-than
           #:s-greater-than
           #:u-greater-than-equal
           #:s-greater-than-equal
           #:u-less-than
           #:s-less-than
           #:u-less-than-equal
           #:s-less-than-equal
           #:f-ord-equal
           #:f-unord-equal
           #:f-ord-not-equal
           #:f-unord-not-equal
           #:f-ord-less-than
           #:f-unord-less-than
           #:f-ord-greater-than
           #:f-unord-greater-than
           #:f-ord-less-than-equal
           #:f-unord-less-than-equal
           #:f-ord-greater-than-equal
           #:f-unord-greater-than-equal
           #:shift-right-logical
           #:shift-right-arithmetic
           #:shift-left-logical
           #:bitwise-or
           #:bitwise-xor
           #:bitwise-and
           #:not
           #:bit-field-insert
           #:bit-field-s-extract
           #:bit-field-u-extract
           #:bit-reverse
           #:bit-count
           #:dp-dx
           #:dp-dy
           #:fwidth
           #:dp-dx-fine
           #:dp-dy-fine
           #:fwidth-fine
           #:dp-dx-coarse
           #:dp-dy-coarse
           #:fwidth-coarse
           #:emit-vertex
           #:end-primitive
           #:emit-stream-vertex
           #:end-stream-primitive
           #:control-barrier
           #:memory-barrier
           #:atomic-load
           #:atomic-store
           #:atomic-exchange
           #:atomic-compare-exchange
           #:atomic-compare-exchange-weak
           #:atomic-i-increment
           #:atomic-i-decrement
           #:atomic-i-add
           #:atomic-i-sub
           #:atomic-s-min
           #:atomic-u-min
           #:atomic-s-max
           #:atomic-u-max
           #:atomic-and
           #:atomic-or
           #:atomic-xor
           #:phi
           #:loop-merge
           #:selection-merge
           #:label
           #:branch
           #:branch-conditional
           #:switch
           #:kill
           #:return
           #:return-value
           #:unreachable
           #:lifetime-start
           #:lifetime-stop
           #:group-async-copy
           #:group-wait-events
           #:group-all
           #:group-any
           #:group-broadcast
           #:group-i-add
           #:group-f-add
           #:group-f-min
           #:group-u-min
           #:group-s-min
           #:group-f-max
           #:group-u-max
           #:group-s-max
           #:read-pipe
           #:write-pipe
           #:reserved-read-pipe
           #:reserved-write-pipe
           #:reserve-read-pipe-packets
           #:reserve-write-pipe-packets
           #:commit-read-pipe
           #:commit-write-pipe
           #:is-valid-reserve-id
           #:get-num-pipe-packets
           #:get-max-pipe-packets
           #:group-reserve-read-pipe-packets
           #:group-reserve-write-pipe-packets
           #:group-commit-read-pipe
           #:group-commit-write-pipe
           #:enqueue-marker
           #:enqueue-kernel
           #:get-kernel-nd-range-sub-group-count
           #:get-kernel-nd-range-max-sub-group-size
           #:get-kernel-work-group-size
           #:get-kernel-preferred-work-group-size-multiple
           #:retain-event
           #:release-event
           #:create-user-event
           #:is-valid-event
           #:set-user-event-status
           #:capture-event-profiling-info
           #:get-default-queue
           #:build-nd-range
           #:image-sparse-sample-implicit-lod
           #:image-sparse-sample-explicit-lod
           #:image-sparse-sample-dref-implicit-lod
           #:image-sparse-sample-dref-explicit-lod
           #:image-sparse-sample-proj-implicit-lod
           #:image-sparse-sample-proj-explicit-lod
           #:image-sparse-sample-proj-dref-implicit-lod
           #:image-sparse-sample-proj-dref-explicit-lod
           #:image-sparse-fetch
           #:image-sparse-gather
           #:image-sparse-dref-gather
           #:image-sparse-texels-resident
           #:no-line
           #:atomic-flag-test-and-set
           #:atomic-flag-clear
           #:image-sparse-read
           #:size-of
           #:type-pipe-storage
           #:constant-pipe-storage
           #:create-pipe-from-pipe-storage
           #:get-kernel-local-size-for-subgroup-count
           #:get-kernel-max-num-subgroups
           #:type-named-barrier
           #:named-barrier-initialize
           #:memory-named-barrier
           #:module-processed
           #:subgroup-ballot-khr
           #:subgroup-first-invocation-khr))
(defpackage #:spirv-glsl450
  (:use )
  (:export #:interpolation-function
           #:float64
           #:round
           #:round-even
           #:trunc
           #:f-abs
           #:s-abs
           #:f-sign
           #:s-sign
           #:floor
           #:ceil
           #:fract
           #:radians
           #:degrees
           #:sin
           #:cos
           #:tan
           #:asin
           #:acos
           #:atan
           #:sinh
           #:cosh
           #:tanh
           #:asinh
           #:acosh
           #:atanh
           #:atan2
           #:pow
           #:exp
           #:log
           #:exp2
           #:log2
           #:sqrt
           #:inverse-sqrt
           #:determinant
           #:matrix-inverse
           #:modf
           #:modf-struct
           #:f-min
           #:u-min
           #:s-min
           #:f-max
           #:u-max
           #:s-max
           #:f-clamp
           #:u-clamp
           #:s-clamp
           #:f-mix
           #:i-mix
           #:step
           #:smooth-step
           #:fma
           #:frexp
           #:frexp-struct
           #:ldexp
           #:pack-snorm-4x8
           #:pack-unorm-4x8
           #:pack-snorm-2x16
           #:pack-unorm-2x16
           #:pack-half-2x16
           #:pack-double-2x32
           #:unpack-snorm-2x16
           #:unpack-unorm-2x16
           #:unpack-half-2x16
           #:unpack-snorm-4x8
           #:unpack-unorm-4x8
           #:unpack-double-2x32
           #:length
           #:distance
           #:cross
           #:normalize
           #:face-forward
           #:reflect
           #:refract
           #:find-i-lsb
           #:find-s-msb
           #:find-u-msb
           #:interpolate-at-centroid
           #:interpolate-at-sample
           #:interpolate-at-offset
           #:n-min
           #:n-max
           #:n-clamp))
